catalog_name: mdl_europe_anz_dev
schema_name: patrick_mlops

repository_name: "Patrick_MLOps"
experiment_name: "/Shared/Hotel_Reservations"
branch: "week2"

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room

cat_features:
  - Booking_ID
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - market_segment_type
  - repeated_guest

target: booking_status
