catalog_name: mdl_europe_anz_dev
schema_name: patrick_mlops
volume_name: mlops_course
table_name: hotel_reservations.csv

repository_name: "Patrick_MLOps"
experiment_name: "/Shared/Hotel_Reservations"
branch: "week2"

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

ab_test_experiment_name: "/Shared/Hotel_Reservations_AB_Testing"

ab_test_parameters_a:
  learning_rate_a: 0.02
  max_depth_a: 6
  n_estimators: 1000

ab_test_parameters_b:
  learning_rate_b: 0.02
  max_depth_b: 10
  n_estimators: 1000

num_features:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - lead_time
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests

cat_features:
  - Booking_ID
  - type_of_meal_plan
  - required_car_parking_space
  - room_type_reserved
  - market_segment_type
  - repeated_guest

func_features:
 - TotalNoNights

target: booking_status
